#!/usr/bin/env bash

export NVIM_APPNAME="${NVIM_APPNAME:-"hvim"}"

# export XDG_CONFIG_HOME="$HOME/.config"
# export XDG_DATA_HOME="$HOME/.local/share"

# echo "XDG_CONFIG_HOME: $XDG_CONFIG_HOME"
# echo "XDG_DATA_HOME: $XDG_DATA_HOME"

exec -a "$NVIM_APPNAME" nvim -u "$HOME/.config/hvim/init.lua" "$@"
