return {
  -- 'Bekaboo/dropbar.nvim',
  -- -- optional, but required for fuzzy finder support
  -- dependencies = {
  --   'nvim-telescope/telescope-fzf-native.nvim'
  -- },
  -- config = function()
  --   vim.ui.select = require'dropbar.utils.menu'.select
  --   require('dropbar').setup({
  --     icons = {
  --       kinds = {
  --         use_devicons = true
  --       }
  --     },
  --     bar = {
  --       hover = true,
  --       padding = { left = 0, right = 0 },
  --       truncate = true,
  --       max_length = 40,
  --     },
  --   })
  -- end
}
